# Symphony - Kitty Colors (Dynamic Template)

cursor                 #c9bfff
cursor_text_color      #31285f

foreground             #e5e1e9
background             #141318
selection_foreground   #e5deff
selection_background   #473f77
url_color              #c9bfff

# black (الخلفيات والرماديات الداكنة)
color0   #141318
color8   #2b292f

# red (الأحمر والتحذيرات)
color1   #ffb4ab
color9   #93000a

# green (الأخضر والنجاح - هنا نربطه بالـ Primary الحقيقي للصورة)
color2   #c9bfff
color10  #c9bfff

# yellow (الأصفر)
color3   #edb8cd
color11  #edb8cd

# blue (الأزرق - نربطه بالـ Secondary ليعطي تباين فرعي)
color4   #c9c3dc
color12  #c9c3dc

# magenta
color5   #5f5790
color13  #e5deff

# cyan
color6   #938f99
color14  #48454e

# white
color7   #c9c5d0
color15  #e5e1e9
