-- This configuration is generated by matugen
-- Changing these variables with matugen still enabled will overwrite them.

image = "/home/klain/Pictures/Wallpapers/dragons_lake_fog_white_boat_person.jpg"

color_background = "rgba(101418ff)"

color_error = "rgba(ffb4abff)"

color_error_container = "rgba(93000aff)"

color_inverse_on_surface = "rgba(2d3135ff)"

color_inverse_primary = "rgba(33618dff)"

color_inverse_surface = "rgba(e0e2e8ff)"

color_on_background = "rgba(e0e2e8ff)"

color_on_error = "rgba(690005ff)"

color_on_error_container = "rgba(ffdad6ff)"

color_on_primary = "rgba(003256ff)"

color_on_primary_container = "rgba(d0e4ffff)"

color_on_primary_fixed = "rgba(001d35ff)"

color_on_primary_fixed_variant = "rgba(154974ff)"

color_on_secondary = "rgba(243140ff)"

color_on_secondary_container = "rgba(d6e4f7ff)"

color_on_secondary_fixed = "rgba(0f1d2aff)"

color_on_secondary_fixed_variant = "rgba(3b4857ff)"

color_on_surface = "rgba(e0e2e8ff)"

color_on_surface_variant = "rgba(c2c7cfff)"

color_on_tertiary = "rgba(3a2a48ff)"

color_on_tertiary_container = "rgba(f1dbffff)"

color_on_tertiary_fixed = "rgba(241532ff)"

color_on_tertiary_fixed_variant = "rgba(514060ff)"

color_outline = "rgba(8c9199ff)"

color_outline_variant = "rgba(42474eff)"

color_primary = "rgba(9ecafcff)"

color_primary_container = "rgba(154974ff)"

color_primary_fixed = "rgba(d0e4ffff)"

color_primary_fixed_dim = "rgba(9ecafcff)"

color_scrim = "rgba(000000ff)"

color_secondary = "rgba(bac8dbff)"

color_secondary_container = "rgba(3b4857ff)"

color_secondary_fixed = "rgba(d6e4f7ff)"

color_secondary_fixed_dim = "rgba(bac8dbff)"

color_shadow = "rgba(000000ff)"

color_source_color = "rgba(68819eff)"

color_surface = "rgba(101418ff)"

color_surface_bright = "rgba(36393eff)"

color_surface_container = "rgba(1d2024ff)"

color_surface_container_high = "rgba(272a2fff)"

color_surface_container_highest = "rgba(32353aff)"

color_surface_container_low = "rgba(191c20ff)"

color_surface_container_lowest = "rgba(0b0e12ff)"

color_surface_dim = "rgba(101418ff)"

color_surface_tint = "rgba(9ecafcff)"

color_surface_variant = "rgba(42474eff)"

color_tertiary = "rgba(d5bee5ff)"

color_tertiary_container = "rgba(514060ff)"

color_tertiary_fixed = "rgba(f1dbffff)"

color_tertiary_fixed_dim = "rgba(d5bee5ff)"
