-- This configuration is generated by matugen
-- Changing these variables with matugen still enabled will overwrite them.

image = "{{image}}"
<* for name, value in colors *>
color_{{name}} = "rgba({{value.default.hex_stripped}}ff)"
<* endfor *>