background-color={{colors.background.default.hex}}
osd-back-color={{colors.surface.default.hex}}
osd-border-color={{colors.shadow.default.hex}}
osd-color={{colors.on_surface.default.hex}}
osd-shadow-color={{colors.shadow.default.hex}}